env:
  MAVEN_LINK: link-to-maven-repo

steps:
  - label: 'Check'
    agents:
      selector: "data"
    commands:
      - "ls -alt ./"
      - "mkdir /tmp/test-results/$BUILDKITE_JOB_ID"
      - "cp -r $(pwd) /tmp/test-results/$BUILDKITE_JOB_ID"
      - "ls -alt /tmp/test-results/$BUILDKITE_JOB_ID/hq-api"
  - wait

  - label: 'Publish'
    agents:
      selector: "data"
    commands:
      - "export MAVEN_VERSION=0.0.1" # Как получить git tag name внутри CI Job?
      - "ls -la ./"
      - "sed 's/VERSION_FROM_CI/'\"$BUILDKITE_COMMIT\"'/' spec/api-hq.yaml > api-hq.yaml"
      - "cat api-hq.yaml"
      - "mv api-hq.yaml spec/api-hq.yaml"
      - "./gradlew openApiGenerate"
      - "mv build/generated/src/main/ ./src/main"
      - "./gradlew jar"
    plugins:
      - docker#v3.12.0:
          image: "openjdk:13"
          volumes:
#            - "/var/run/docker.sock:/var/run/docker.sock"
            - "/tmp/test-results/$BUILDKITE_JOB_ID/hq-api:/workdir"
          propagate-environment: true
          mount-checkout: false
          workdir: /workdir
