env:
  MAVEN_REGISTRY: https://nexus.flocktory.com/nexus/content/repositories/releases/
  NPM_REGISTRY: nexus3.flocktory.com/repository/npm-hosted/

steps:
  - label: ServerStub
#      if: build.tag != null
    commands:
#      - export API_VERSION=$BUILDKITE_TAG
      - export API_VERSION=0.0.5
      - ./gradlew generateServerStub -Ptype=Server
      - ./gradlew publish -Ptype=Server
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          region: eu-west-1
          json-to-env:
            - secret-id: "/prod/services/nexus"
      - docker-compose#v3.9.0:
          run: openjdk
          config: docker-compose.ci.yml
          env:
            - BUILDKITE_TAG
            - MAVEN_REGISTRY
            - NEXUS_USERNAME
            - NEXUS_PASSWORD
  - label: JavaCLient
#    if: build.tag != null
    commands:
#      - export API_VERSION=$BUILDKITE_TAG
      - export API_VERSION=0.0.5
      - ./gradlew generateJavaClient -Ptype=Client
      - ./gradlew publish -Ptype=Client
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          region: eu-west-1
          json-to-env:
            - secret-id: "/prod/services/nexus"
      - docker-compose#v3.9.0:
          run: openjdk
          config: docker-compose.ci.yml
          env:
            - BUILDKITE_TAG
            - MAVEN_REGISTRY
            - NEXUS_USERNAME
            - NEXUS_PASSWORD
  - label: JavaScriptCLientGenerate
#    if: build.tag != null
    commands:
#      - export API_VERSION=$BUILDKITE_TAG
      - export API_VERSION=0.0.5
      - ./gradlew generateJavaScriptClient -Ptype=Client
      - buildkite-agent artifact upload hq-api-js-client.tar
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          region: eu-west-1
          json-to-env:
            - secret-id: "/prod/services/nexus"
            - secret-id: "/prod/services/buildkite"
      - docker-compose#v3.9.0:
          run: node
          config: docker-compose.ci.yml
          args:
            - TOKEN=$TOKEN
          env:
            - MAVEN_REGISTRY
            - NEXUS_USERNAME
            - NEXUS_PASSWORD
            - BUILDKITE_TAG
            - BUILDKITE_JOB_ID
            - BUILDKITE_BUILD_ID
            - BUILDKITE_AGENT_ACCESS_TOKEN
  - wait
  - label: JavaScriptCLientPublish
#    if: build.tag != null
    commands:
      - buildkite-agent artifact download hq-api-js-client.tar .
      - tar -xf hq-api-js-client.tar && rm hq-api-js-client.tar
      - npm install babel-cli babel-core
      - echo "//$NPM_REGISTRY:_authToken=NpmToken.$NPM_TOKEN" > .npmrc
      - npm publish --registry=$NPM_REGISTRY
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          region: eu-west-1
          json-to-env:
            - secret-id: "/prod/services/buildkite"
            - secret-id: "/prod/services/npm"
      - docker-compose#v3.9.0:
          run: node
          config: docker-compose.ci.yml
          args:
            - TOKEN=$TOKEN
          env:
            - BUILDKITE_TAG
            - BUILDKITE_JOB_ID
            - BUILDKITE_BUILD_ID
            - BUILDKITE_AGENT_ACCESS_TOKEN
            - NPM_REGISTRY
            - NPM_TOKEN
