env:
  MAVEN_LINK: link-to-maven-repo

steps:
  - label: 'Publish'
    commands:
#      - "export MAVEN_VERSION=0.0.1" # Как получить git tag name внутри CI Job?
      - "java --version"
      - "ls -la"
      - "cd spec"
      - "cat api-hq.yaml"
      - "sed 's/VERSION_FROM_CI/'\"$MAVEN_VERSION\"'/' spec/api-hq.yaml > api-hq.yaml"
      - "mv api-hq.yaml spec/api-hq.yaml"
      - "./gradlew openApiGenerate"
      - "mv build/generated/src/main/ ./src/main"
      - "./gradlew jar"
    plugins:
      - docker#v3.12.0:
          image: "openjdk:13"
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "/buildkite/builds:/buildkite/builds"
          propagate-environment: true
