env:
  MAVEN_REPOSITORY_LINK: https://nexus.flocktory.com/nexus/content/repositories/releases/

steps:
  - label: ServerStub
    if: build.tag != null
    commands:
      - export API_VERSION=$BUILDKITE_TAG
      - ./gradlew generateServerStub -Ptype=Server
      - ./gradlew publish -Ptype=Server
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          region: eu-west-1
          json-to-env:
            - secret-id: "/prod/services/nexus"
      - docker-compose#v3.9.0:
          run: openjdk
          config: docker-compose.ci.yml
          env:
            - BUILDKITE_TAG
            - MAVEN_REPOSITORY_LINK
            - NEXUS_USERNAME
            - NEXUS_PASSWORD
  - label: JavaCLient
    if: build.tag != null
    commands:
      - export API_VERSION=$BUILDKITE_TAG
      - ./gradlew generateJavaClient -Ptype=Client
      - ./gradlew publish -Ptype=Client
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          region: eu-west-1
          json-to-env:
            - secret-id: "/prod/services/nexus"
      - docker-compose#v3.9.0:
          run: openjdk
          config: docker-compose.ci.yml
          env:
            - BUILDKITE_TAG
            - MAVEN_REPOSITORY_LINK
            - NEXUS_USERNAME
            - NEXUS_PASSWORD
