env:
  MAVEN_REGISTRY: https://nexus.flocktory.com/nexus/content/repositories/releases/
  NPM_REGISTRY: https://nexus3.flocktory.com/repository/npm-hosted/

steps:
#  - label: ServerStub
  #    if: build.tag != null
  #    commands:
  #      - export API_VERSION=$BUILDKITE_TAG
  #      - ./gradlew generateServerStub -Ptype=Server
  #      - ./gradlew publish -Ptype=Server
  #    plugins:
  #      - seek-oss/aws-sm#v2.3.1:
  #          region: eu-west-1
  #          json-to-env:
  #            - secret-id: "/prod/services/nexus"
  #      - docker-compose#v3.9.0:
  #          run: openjdk
  #          config: docker-compose.ci.yml
  #          env:
  #            - BUILDKITE_TAG
  #            - MAVEN_REGISTRY
  #            - NEXUS_USERNAME
  #            - NEXUS_PASSWORD
  #  - label: JavaCLient
  #    if: build.tag != null
  #    commands:
  #      - export API_VERSION=$BUILDKITE_TAG
  #      - ./gradlew generateJavaClient -Ptype=Client
  #      - ./gradlew publish -Ptype=Client
  #    plugins:
  #      - seek-oss/aws-sm#v2.3.1:
  #          region: eu-west-1
  #          json-to-env:
  #            - secret-id: "/prod/services/nexus"
  #      - docker-compose#v3.9.0:
  #          run: openjdk
  #          config: docker-compose.ci.yml
  #          env:
  #            - BUILDKITE_TAG
  #            - MAVEN_REGISTRY
  #            - NEXUS_USERNAME
  #            - NEXUS_PASSWORD
#  - label: JavaScriptCLientGenerate
#      #      if: build.tag != null
#    commands:
#      #        - export API_VERSION=$BUILDKITE_TAG
#      - export API_VERSION=0.0.1
#      - ./gradlew generateJavaScriptClient -Ptype=Client
#      - bash -c "`curl -sL https://raw.githubusercontent.com/buildkite/agent/main/install.sh`"
#      - mv build/tar/hq-api-js-client.tar hq-api-js-client.tar
#      - ~/.buildkite-agent/bin/buildkite-agent artifact upload hq-api-js-client.tar
#    plugins:
#      - seek-oss/aws-sm#v2.3.1:
#          region: eu-west-1
#          json-to-env:
#            - secret-id: "/prod/services/nexus"
#            - secret-id: "/prod/services/buildkite"
#      - docker-compose#v3.9.0:
#          run: openjdk
#          config: docker-compose.ci.yml
#          env:
#            - BUILDKITE_TAG
#            - MAVEN_REGISTRY
#            - NEXUS_USERNAME
#            - NEXUS_PASSWORD
#            - TOKEN
#            - BUILDKITE_BRANCH
#            - BUILDKITE_JOB_ID
#            - BUILDKITE_BUILD_ID
#            - BUILDKITE_AGENT_ACCESS_TOKEN
#  - wait
  - label: JavaScriptCLientPublish
    commands:
#      - export API_VERSION=$BUILDKITE_TAG
      - export API_VERSION=0.0.1
      - npm --version
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          region: eu-west-1
          json-to-env:
            - secret-id: "/prod/services/buildkite"
            - secret-id: "/prod/services/npm"
      - docker-compose#v3.9.0:
          run: openjdk
          config: ci/js/docker-compose.yml
          args:
            - TOKEN=$TOKEN
          env:
            - BUILDKITE_TAG
            - BUILDKITE_JOB_ID
            - BUILDKITE_BUILD_ID
            - BUILDKITE_AGENT_ACCESS_TOKEN
            - NPM_USER
            - NPM_PASS
            - NPM_EMAIL
            - NPM_REGISTRY
#  - label: JavaScriptCLientPublish
##    if: build.branch == "main"
#    commands:
#      - ls -la
#      - npm install -g npm-cli-login
#      - npm-cli-login -u $$NPM_USER -p $$NPM_PASS -e $$NPM_EMAIL -r $$NPM_REGISTRY
##      - bash -c "`curl -sL https://raw.githubusercontent.com/buildkite/agent/main/install.sh`"
##      - ~/.buildkite-agent/bin/buildkite-agent artifact download hq-api-js-client.tar
#      - ls -la
#      - cd build/tar/
#      - tar -xf hq-api-js-client.tar
#      - buildkite-agent --help
#      - npm publish
#    plugins:
#      - seek-oss/aws-sm#v2.3.1:
#          region: eu-west-1
#          json-to-env:
#            - secret-id: "/prod/services/buildkite"
#            - secret-id: "/prod/services/npm"
#      - docker#v3.12.0:
#          image: "node:17"
#          always-pull: true
#          mount-checkout: true
#          mount-buildkite-agent: true
#          environment:
#            - "TOKEN"
#            - "BUILDKITE_TAG"
#            - "BUILDKITE_JOB_ID"
#            - "BUILDKITE_BUILD_ID"
#            - "BUILDKITE_AGENT_ACCESS_TOKEN"
#            - "NPM_USER"
#            - "NPM_PASS"
#            - "NPM_EMAIL"
#            - "NPM_REGISTRY"
