env:
  MAVEN_LINK: link-to-maven-repo

steps:
  - label: 'Publish'
    commands:
      - "java --version"
      - "pwd"
      - "ls -la"
    plugins:
      - docker-compose#v3.9.0:
          run: openjdk
          config: docker-compose.ci.yml
