env:
  MAVEN_REPOSITORY_LINK: https://nexus.flocktory.com/nexus/content/repositories/releases/

steps:
  - label: Publish
    if: build.tag != null
    commands:
      - export API_VERSION=$BUILDKITE_TAG
      - sed 's/VERSION_FROM_CI/'\"$API_VERSION\"'/' spec/api-hq.yaml > api-hq.yaml
      - mv api-hq.yaml spec/api-hq.yaml
      - ./gradlew openApiGenerate
      - mv build/generated/src/main/ ./src/main
      - ./gradlew publish
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          region: eu-west-1
          json-to-env:
            - secret-id: "/prod/services/nexus"
      - docker-compose#v3.9.0:
          run: openjdk
          config: docker-compose.ci.yml
          env:
            - BUILDKITE_TAG
            - MAVEN_REPOSITORY_LINK
            - NEXUS_USERNAME
            - NEXUS_PASSWORD

