---
openapi: 3.0.0
info:
  title: HQ API Spesification
  version: unknown
externalDocs:
  description: OpenAPI Specification
  url: https://swagger.io/specification/
servers:
  - url: https://hq.api.floctory.ru/
tags:
  - name: user
    description: Operations about user
paths:
  /user:
    post:
      tags:
        - user
      summary: Create user
      description: This can only be done by the logged in user.
      operationId: createUser
      requestBody:
        description: Created user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        default:
          description: successful operation
components:
  schemas:
    User:
      type: object
      properties:
        login:
          type: string
        personalData:
          $ref: '#/components/schemas/PersonalData'
        contactInformation:
          $ref: '#/components/schemas/ContactInformation'
    PersonalData:
      type: object
      properties:
        firstName:
          type: string
        secondName:
          type: string
        surname:
          type: string
    ContactInformation:
      type: object
      properties:
        email:
          type: string
        phone:
          type: string